"""bpl-cards project — generated by `paratext new`. Edit schema.py and prompt.md."""

from __future__ import annotations

from paratext.projects import Project, load_prompt
from paratext.sources import image_source

from .schema import Record

PROJECT = Project(
    name="bpl-cards",
    schema_version="v1",
    prompt=load_prompt(__file__),
    schema=Record,
    source=image_source(verso_filter=False, crop=False),
)
